### ISSUE TITLE
TS Import Issue

### ISSUE THREAD

**Issue by erik-slack** [flamelink/flamelink-js-sdk#108]
The docs say to use 
`import flamelink from 'flamelink';`

but because of the default rule 

`"allowSyntheticDefaultImports": false` 

I get this from my tslint:

![image](https://user-images.githubusercontent.com/8229820/69304977-c5101700-0bdf-11ea-9738-709dff4d0bb3.png)

So changing it to 

`import * as flamelink from 'flamelink/app';`

was what I figured would fix it, but then I get this at runtime:

`TypeError: flamelink_app__WEBPACK_IMPORTED_MODULE_7__ is not a function`
![image](https://user-images.githubusercontent.com/8229820/69305097-0dc7d000-0be0-11ea-98a6-cca674b21a68.png)

I can bypass this issue by adding 
`"allowSyntheticDefaultImports": true`
in my tsconfig.json to `compilerOptions`.  But that just seems wrong.

Am I doing this wrong?

**Comment by jperasmus** [comment]
Hi Erik, no, you are doing it right :)

Flamelink's export requires either synthetic default imports or the `esModuleInterop` flag to be enabled. This is because of the design decision we made to have the main export the Flamelink app factory function, ie. `flamelink({ ...config })`. I'm not sure at this stage if it is the best. We've considered changing it to be similar to how Firebase's SDK works, which will then export an object and you have to call the `initializeApp` method on it, ie. `firebase.initializeApp({ ...config })`.

Does the `allowSyntheticDefaultImports` break anything for you?

**Comment by erik-slack** [comment]
No it doesn't, it just throws a linter error.  I'll set it to allowed then.  Thanks, it helps knowing you've made it that way on purpose.

**Comment by jperasmus** [comment]
Do you perhaps have more info on what type of bugs that linting rule would catch? I'm not aware of any specific problems with using synthetic default imports.

**Comment by erik-slack** [comment]
After reading up more about it I think you're good.  Sorry for the snipe hunt!

My source:
https://github.com/Microsoft/TypeScript/issues/10895
