### ISSUE TITLE
provide npm package when ready for testing

### ISSUE THREAD

**Issue by robertbaker** [flamelink/flamelink-js-sdk#33]

**Comment by jperasmus** [comment]
Hi, @robertbaker, thanks for opening this issue. We'll make the package available as an alpha release within the next couple of days. Would be great to get your feedback then. Will post here once it is ready.

**Comment by jperasmus** [comment]
If you feel particularly adventurous, you can try out the new SDK now available as a pre-release. (`npm i flamelink@next`)

Disclaimer: I do NOT recommend you use it in any production code just yet. It is brand new and will still undergo heavy testing before it will be generally available. Since it is an alpha release, things might (and probably will!) change without notice.

If you do choose to check it out, please log any issues you find.

Thanks
