### ISSUE TITLE
Order field not automatically created

### ISSUE THREAD

**Issue by charbelalkazzi** [flamelink/flamelink-js-sdk#71]
After adding the entries to the CMS, the items created do not have an 'order' field created unless their order is manually changed.
So currently, to be able to list the ordered entries on the website using: orderBy: 'order', I'm having to edit the order of the entries every time I add one.

Please check it, 

Thanks

C.

**Comment by jperasmus** [comment]
Thanks for logging this issue, @charbelalkazzi 

We'll look into it.

**Comment by jordanch** [comment]
Hi @charbelalkazzi,

What is your expected behaviour for content creation with regards to the `order` property? E.g. Do you expect every entry created to be created with an order property where the value is the number of entries belong to the schema minus one (since the order property value starts from 0)?

Do you expect the parentId property to also be set with an initial value of 0?

**Comment by jordanch** [comment]
The following implementation has been released:

New content entries get `order` and `parentId` properties set to 0. When a collection/form is "sorted" using the Structure Collection feature, each entry's `order` and `parentId` field will be updated appropriately.

**Comment by jordanch** [comment]
@jperasmus happy to close?

**Comment by jperasmus** [comment]
Thanks, Jordan.
